# Generated by Django 2.2 on 2020-11-10 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_nac', models.DateField(blank=True, help_text='Fecha de nacimiento: (DD/MM/AAAA)', null=True, verbose_name='Fecha de nacimiento')),
                ('f_alta', models.DateField(auto_now_add=True)),
                ('f_acceso', models.DateTimeField(auto_now=True)),
                ('puesto', models.CharField(choices=[('GERENCIA', 'GERENCIA'), ('SECRETARIA', 'SECRETARIA'), ('MEDICO', 'MEDICO'), ('TECNICO', 'TECNICO'), ('VENTAS', 'VENTAS')], default='VENTAS', max_length=20, verbose_name='Puesto')),
                ('telefono', models.CharField(blank=True, help_text='(i.e 2923-4123456)', max_length=12, null=True, verbose_name='Teléfono')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'ordering': ['usuario'],
            },
        ),
    ]
