# Generated by Django 2.2 on 2020-11-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='interno',
            field=models.CharField(blank=True, help_text='(i.e 1234)', max_length=4, null=True, verbose_name='Interno Tel.'),
        ),
    ]
