# Generated by Django 2.2 on 2020-11-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0005_auto_20201110_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='historia',
            name='tratamiento',
            field=models.TextField(blank=True, null=True, verbose_name='Tratamiento'),
        ),
        migrations.AlterField(
            model_name='historia',
            name='enf_actual',
            field=models.TextField(blank=True, null=True, verbose_name='Enfermedad Actual'),
        ),
        migrations.AlterField(
            model_name='historia',
            name='motivo',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de la consulta'),
        ),
    ]
