# Generated by Django 2.2 on 2020-11-13 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0007_auto_20201112_2037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['dni'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
    ]
