# Generated by Django 2.2 on 2020-11-13 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0008_auto_20201113_0733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['usuario'], 'permissions': (('Medico', 'Es un medico'), ('Secretaria', 'Es secretaria')), 'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
    ]
