# Generated by Django 2.2 on 2020-11-13 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0009_auto_20201113_0817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['usuario'], 'permissions': (('Gerencia', 'Es gerente'), ('Secretaria', 'Es secretaria'), ('Medico', 'Es un medico'), ('Tecnico', 'Es un tecnico'), ('Ventas', 'Es un vendedor')), 'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
    ]
