# Generated by Django 2.2 on 2020-11-13 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0010_auto_20201113_1207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['usuario'], 'permissions': (('gerencia', 'Es gerente'), ('secretaria', 'Es secretaria'), ('medico', 'Es un medico'), ('tecnico', 'Es un tecnico'), ('ventas', 'Es un vendedor')), 'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
    ]
