# Generated by Django 2.2 on 2020-11-14 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0011_auto_20201113_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha: (DD/MM/AAAA)', verbose_name='Fecha')),
                ('hora', models.TimeField(help_text='Hora: (HH/MM)', verbose_name='Hora')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appweb.Paciente')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['fecha', 'hora'],
            },
        ),
    ]
