# Generated by Django 2.2 on 2020-11-14 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appweb', '0012_turno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('cuit', models.CharField(blank=True, max_length=13, null=True, verbose_name='CUIT')),
                ('direccion', models.CharField(max_length=250, verbose_name='Dirección')),
                ('cod_postal', models.CharField(blank=True, max_length=10, null=True, verbose_name='C. Postal')),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ciudad')),
                ('provincia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Provincia')),
                ('pais', models.CharField(blank=True, max_length=50, null=True, verbose_name='País')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telefono1', models.CharField(blank=True, max_length=12, null=True, verbose_name='Teléfono')),
                ('telefono2', models.CharField(blank=True, max_length=12, null=True, verbose_name='Teléfono')),
                ('contacto', models.CharField(blank=True, max_length=250, null=True, verbose_name='Contacto')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['dni'], 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AddField(
            model_name='turno',
            name='medico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('marca', models.CharField(blank=True, max_length=200, null=True, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Modelo')),
                ('clasificacion', models.CharField(blank=True, max_length=80, null=True, verbose_name='Clasificación')),
                ('izquierdo', models.BooleanField(default=False, verbose_name='Izquierdo')),
                ('derecho', models.BooleanField(default=False, verbose_name='Derecho')),
                ('lejos', models.BooleanField(default=False, verbose_name='Lejos')),
                ('cerca', models.BooleanField(default=False, verbose_name='Lejos')),
                ('armazon', models.BooleanField(default=False, verbose_name='Armazón')),
                ('otros', models.TextField(blank=True, null=True, verbose_name='Otros')),
                ('stock', models.PositiveSmallIntegerField(verbose_name='Stock')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Precio unitario')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appweb.Proveedor')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField(verbose_name='Cantidad')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Precio unitario')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('PEDIDO', 'PEDIDO'), ('TALLER', 'TALLER'), ('FINALIZADO', 'FINALIZADO')], default='PENDIENTE', max_length=10, verbose_name='Estado')),
                ('nota', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appweb.Producto')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['producto'],
            },
        ),
        migrations.AddField(
            model_name='paciente',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appweb.Pedido'),
        ),
    ]
