# Generated by Django 2.2 on 2020-11-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0013_auto_20201114_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cerca',
            field=models.BooleanField(default=False, verbose_name='Cerca'),
        ),
    ]
