# Generated by Django 2.2 on 2020-11-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0017_auto_20201114_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='concurrio',
            field=models.BooleanField(default=False, verbose_name='Concurrió'),
        ),
    ]
