# Generated by Django 2.2 on 2020-11-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0021_auto_20201121_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='vendedor',
            field=models.CharField(default=1, max_length=150, verbose_name='vendedor'),
            preserve_default=False,
        ),
    ]
