# Generated by Django 2.2 on 2020-11-23 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0023_auto_20201123_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historia',
            options={'ordering': ['-fecha'], 'verbose_name': 'Historia', 'verbose_name_plural': 'Historias'},
        ),
    ]
