# Generated by Django 2.2 on 2020-11-23 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0024_auto_20201123_1055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-fecha'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
    ]
