# Generated by Django 2.2 on 2020-11-23 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0026_auto_20201123_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='medico',
        ),
    ]
