# Generated by Django 2.2 on 2020-11-23 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0028_turno_medico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appweb.Perfil'),
        ),
    ]
