# Generated by Django 2.2 on 2020-11-23 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0029_auto_20201123_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appweb.Perfil'),
        ),
    ]
