# Generated by Django 2.2 on 2020-11-24 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0032_auto_20201124_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='producto',
        ),
        migrations.AddField(
            model_name='pedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7, verbose_name='Venta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appweb.Perfil'),
        ),
        migrations.CreateModel(
            name='RenglonPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField(default=1, verbose_name='Cantidad')),
                ('total', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Total')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appweb.Pedido')),
                ('producto', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='appweb.Producto')),
            ],
            options={
                'verbose_name': 'Renglón del pedido',
                'verbose_name_plural': 'Renglones de los pedidos',
            },
        ),
    ]
