# Generated by Django 2.2 on 2020-11-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0033_auto_20201124_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Venta Total $'),
        ),
    ]
