# Generated by Django 2.2 on 2020-11-25 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0034_auto_20201124_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='renglonpedido',
            name='total',
        ),
        migrations.AddField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Venta Total $'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='renglonpedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7, verbose_name='Subtotal'),
            preserve_default=False,
        ),
    ]
