# Generated by Django 2.2 on 2020-11-25 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0035_auto_20201124_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='renglonpedido',
            options={'verbose_name': 'Renglon_pedido', 'verbose_name_plural': 'Renglones_pedidos'},
        ),
    ]
