# Generated by Django 2.2 on 2020-11-25 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0036_auto_20201124_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Venta Total $'),
        ),
    ]
