# Generated by Django 2.2 on 2020-11-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0037_auto_20201124_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renglonpedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Subtotal'),
        ),
    ]
